apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-3718th
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-3718th
  namespace: my-nginx-3718th
  labels:
    name: nginx-3718th
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-3718th
  template:
    metadata:
      namespace: my-nginx-3718th
      labels:
        name: nginx-3718th
    spec:
      containers:
      - name: nginx-3718th
        image: nginx
        ports:
        - containerPort: 80

